music4you/Models/Album.cs
using music4you.Data;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace music4you.Models
{
    public class Album
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Author { get; set; }
        public int Year { get; set; }
        public Genre Genre { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<Rating> ?Ratings { get; set; }
        public IEnumerable<Review> ?Reviews { get; set; }
    }
}

music4you/ViewModels/AlbumViewModel.cs
using music4you.Data;
using music4you.Models;
using System.ComponentModel.DataAnnotations;

namespace music4you.ViewModels
{
    public class AlbumViewModel
    {
        public int Id { get; set; } 
        public string Name { get; set; }
        public string Author { get; set; }
        public int Year { get; set; }
        public Genre Genre { get; set; }
        public string ImageUrl { get; set; }
        public List<Rating> ?Ratings { get; set; }
        public List<Review> ?Reviews { get; set; }
        public Rating ?UserRating { get; set; }

        public bool IsReviewed { get; set; } = false;
    }
}

music4you/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using music4you.Data;
using music4you.Interface;
using music4you.Models;
using music4you.Repository;
using music4you.ViewModels;
using System.Text;

namespace music4you.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumRepository _albumRepository;
        private readonly UserManager<AppUser> _userManager;

        public AlbumController(IAlbumRepository albumRepository,
                                UserManager<AppUser> userManager) 
        {
            _albumRepository = albumRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string? search)
        {
            if (string.IsNullOrEmpty(search))
            {
                var albums = await _albumRepository.GetAll();
                return View(albums);
            }
            else
            {
                var albums = await _albumRepository.GetFilteredByName(search);
                return View(albums);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            Album album = await _albumRepository.GetByIdExtended(id);

            if(album == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            string userId = _userManager.GetUserId(User);

            if(userId != null)
            {
                Rating userRating = await _albumRepository.GetUserRating(id, userId);
                var review = await _albumRepository.GetAlbumUserReview(userId, album.Id);

                bool isReviewed = (review != null);

                AlbumViewModel vm = new AlbumViewModel()
                {
                    Id = id,
                    Name = album.Name,
                    Author = album.Author,
                    Year = album.Year,
                    Genre = album.Genre,
                    ImageUrl = album.ImageUrl,
                    Ratings = album.Ratings.ToList(),
                    Reviews = album.Reviews.ToList(),
                    UserRating = userRating,
                    IsReviewed = isReviewed
                };
                return View(vm);
            }
            else
            {
                AlbumViewModel vm = new AlbumViewModel()
                {
                    Id = id,
                    Name = album.Name,
                    Author = album.Author,
                    Year = album.Year,
                    Genre = album.Genre,
                    ImageUrl = album.ImageUrl,
                    Ratings = album.Ratings.ToList(),
                    Reviews = album.Reviews.ToList(),
                    IsReviewed = false
                };
                return View(vm);
            }
        }

        public async Task<IActionResult> Create()
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            AlbumCreateViewModel vm = new AlbumCreateViewModel();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AlbumCreateViewModel vm)
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                if(!(await ValidateImageAsync(vm.ImageUrl)))
                {
                    TempData["Error"] = "Podaj poprawny link do obrazka. Najczęściej kończy się na '.jpg', '.png', itd..";
                    return View(vm);
                }
                Album newAlbum = new Album()
                {
                    Name = vm.Name,
                    Author = vm.Author,
                    Year = vm.Year,
                    Genre = vm.Genre,
                    ImageUrl = vm.ImageUrl
                };

                if (_albumRepository.Add(newAlbum))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewData["Error"] = "Nie powiodło się dodawanie albumu";
                    return View(vm);
                }

                
            }
            else
            {
                return View(vm);
            }
        }

        private async Task<bool> ValidateImageAsync(string imageUrl)
        {
            using (var httpClient = new HttpClient())
            {
                try
                {
                    var request = new HttpRequestMessage(HttpMethod.Head, imageUrl);
                    var response = await httpClient.SendAsync(request);

                    if (response.IsSuccessStatusCode)
                    {
                        var contentType = response.Content.Headers.ContentType.MediaType;

                        if (contentType.StartsWith("image/"))
                        {
                            return true;
                        }
                    }
                }
                catch
                {
                }
            }

            return false;
        }
    }
}

music4you/Controllers/RatingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using music4you.Interface;
using music4you.Models;

namespace music4you.Controllers
{
    public class RatingController : Controller
    {
        private readonly IRatingRepository _ratingRepository;
        private readonly UserManager<AppUser> _userManager;

        public RatingController(IRatingRepository ratingRepository, UserManager<AppUser> userManager)
        {
            _ratingRepository = ratingRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Create(int albumId, int value)
        {
            AppUser appUser;

            if (User.Identity.IsAuthenticated)
            {
                appUser = await _userManager.GetUserAsync(User);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            

            if (appUser != null)
            {
                Rating rating = new Rating()
                {
                    Value = value,
                    AlbumId = albumId,
                    AppUser = appUser
                };

                if (!_ratingRepository.Add(rating))
                {
                    ViewData["Error"] = "Nie udało się dodać oceny albumu";
                }        
                return RedirectToAction("Details", "Album", new { id = albumId });
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public async Task<IActionResult> Update(int albumId, int ratingId, int value)
        {
            AppUser appUser;

            if (User.Identity.IsAuthenticated)
            {
                appUser = await _userManager.GetUserAsync(User);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

            if (appUser != null)
            {
                Rating rating = await _ratingRepository.GetById(ratingId);

                if (rating != null)
                {
                    rating.Value = value;
                    if (!_ratingRepository.Update(rating))
                    {
                        ViewData["Error"] = "Nie udało się dodać oceny albumu";
                    }
                    return RedirectToAction("Details", "Album", new { id = albumId });
                }
                ViewData["Error"] = "Nie udało się dodać oceny albumu";
                return RedirectToAction("Details", "Album", new { id = albumId });
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
    }
}

music4you/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using music4you.Interface;
using music4you.Migrations;
using music4you.Models;
using music4you.ViewModels;

namespace music4you.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewRepository _reviewRepository;
        private readonly UserManager<AppUser> _userManager;
        private readonly IAlbumRepository _albumRepository;
        private readonly ICommentRepository _commentRepository;

        public ReviewController(IReviewRepository reviewRepository, 
                                UserManager<AppUser> userManager, 
                                IAlbumRepository albumRepository,
                                ICommentRepository commentRepository)
        {
            _reviewRepository = reviewRepository;
            _userManager = userManager;
            _albumRepository = albumRepository;
            _commentRepository = commentRepository;
        }

        public async Task<IActionResult> Create(int albumId)
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var review = await _albumRepository.GetAlbumUserReview(user.Id, albumId);

            if(review != null)
            {
                return Forbid();
            }

            Album album = await _albumRepository.GetById(albumId);

            ReviewCreateViewModel vm = new ReviewCreateViewModel()
            {
                Album = album
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReviewCreateViewModel vm)
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var reviewTest = await _albumRepository.GetAlbumUserReview(user.Id, vm.AlbumId);

            if (reviewTest != null)
            {
                return Forbid();
            }

            if (ModelState.IsValid)
            {
                Review review = new Review()
                {
                    Title = vm.Title,
                    Content = vm.Content,
                    Value = vm.Value,
                    AlbumId = vm.AlbumId,
                    AppUserId = user.Id,
                    CreatedAt = DateTime.Now
                };
                if(await _reviewRepository.Add(review))
                {
                    return RedirectToAction("Details", "Album", new { id = vm.AlbumId });
                }
                
            }
            Album album = await _albumRepository.GetById(vm.AlbumId);
            vm.Album = album;
            return View(vm);

        }

        public async Task<IActionResult> Edit(int id)
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Error401", "Error");
            }

            Review review = await _reviewRepository.GetByIdWithAlbumAsync(id);

            if(user.Id != review.AppUserId)
            {
                return RedirectToAction("Error403", "Error");
            }

            ReviewEditViewModel vm = new ReviewEditViewModel()
            {
                Id = review.Id,
                AlbumId = review.AlbumId,
                Album = review.Album,
                Content = review.Content,
                Title = review.Title,
                Value = review.Value,
                CreatedAt = review.CreatedAt
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ReviewEditViewModel vm)
        {
            if(!ModelState.IsValid) 
            {
                return View(vm);
            }

            Review review = await _reviewRepository.GetByIdAsync(vm.Id);

            review.Content = vm.Content;
            review.Title = vm.Title;
            review.Value = vm.Value;
            review.Id = vm.Id;

            await _reviewRepository.Update(review);
            return RedirectToAction("Details", "Account");
        }

        public async Task<IActionResult> Delete(int id)
        {
            AppUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Error401", "Error");
            }

            Review review = await _reviewRepository.GetByIdWithCommentsAsync(id);

            if(review == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            if (user.Id != review.AppUserId)
            {
                return RedirectToAction("Error403", "Error");
            }

            List<Comment> comments = review.Comments.ToList();

            if(comments.Count > 0)
            {
                foreach (Comment comment in comments)
                {
                    _commentRepository.Delete(comment);
                }
            }
            

            _reviewRepository.Delete(review);
            return RedirectToAction("Details", "Account");
        }

        public async Task<IActionResult> Details(int id)
        {
            Review review = await _reviewRepository.GetByIdWithCommentsAsync(id);
            ReviewViewModel vm = new ReviewViewModel()
            {
                Id = id,
                Title = review.Title,
                Content = review.Content,
                Value = review.Value,
                Album = review.Album,
                AlbumId= review.AlbumId,
                CreatedAt = review.CreatedAt,
                AppUser = review.AppUser,
                Comments = review.Comments.ToList()
            };
            return View(vm);
        }
    }
}

music4you/Views/Album/Create.cshtml
@using music4you.Data
@using music4you.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model AlbumCreateViewModel

@if (TempData["Error"] != null)
{
    <div class="mx-auto max-w-lg space-y-4 rounded-xl bg-red-200 p-3">
        <span class="text-red-800"><b>Błąd!</b> - @TempData["Error"] </span>
    </div>
}

<form method="post" asp-action="Create" class="mx-auto max-w-lg space-y-4 rounded p-6">
    <h3 class="left-2 text-3xl font-semibold text-gray-700">Dodaj nowy album</h3>
    <div class="mt-3">
        <label asp-for="Name" class="block text-sm font-medium text-gray-700">Nazwa albumu</label>
        <input asp-for="Name" class="mt-1 block w-full rounded border-gray-300 p-1 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500" />
        <span asp-validation-for="Name" class="text-sm text-red-600"></span>
    </div>

    <!-- Author -->
    <div>
        <label asp-for="Author" class="block text-sm font-medium text-gray-700">Autor</label>
        <input asp-for="Author" class="mt-1 block w-full rounded border-gray-300 p-1 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500" />
        <span asp-validation-for="Author" class="text-sm text-red-600"></span>
    </div>

    <!-- Genre -->
    <div class="w-full sm:w-1/3">
        <label asp-for="Genre" class="block text-sm font-medium text-gray-700">Gatunek</label>
        <select asp-for="Genre" asp-items="@Html.GetEnumSelectList<Genre>()" class="mt-1 block w-full rounded border-gray-300 p-1 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-gray-900">
        </select>
    </div>

    <!-- Year -->
    <div class="w-full sm:w-1/3">
        <label asp-for="Year" class="block text-sm font-medium text-gray-700">Rok wydania</label>
        <input asp-for="Year" class="mt-1 block w-full rounded border-gray-300 p-1 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500" />
        <span asp-validation-for="Year" class="text-sm text-red-600"></span>
    </div>

    <!-- Image URL -->
    <div>
        <label asp-for="ImageUrl" class="block text-sm font-medium text-gray-700">URL obrazka</label>
        <input asp-for="ImageUrl" class="mt-1 block w-full rounded border-gray-300 p-1 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500" />
        <span asp-validation-for="ImageUrl" class="text-sm text-red-600"></span>
    </div>

    <!-- Submit Button -->
    <div class="pt-8 text-center">
        <input type="submit" value="Dodaj album" class="rounded bg-blue-600 px-6 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2" />
    </div>
</form>

music4you/Views/Album/Details.cshtml
@using music4you.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model AlbumViewModel

<div class="main-container">
    <section class="py-2">
        <div class="container mx-auto px-2">
            <div class="grid-cols-1 grid gap-10 md:grid-cols-2 lg:grid-cols-3">
                <!-- Left Column -->
                <div class="overflow-hidden rounded bg-white shadow">
                    <img alt="Image" id="mainImage" src="@Model.ImageUrl" class="h-auto w-full rounded-t object-cover" />
                    <div class="p-4">
                        <p class="mb-1 mt-1 text-lg"><b><i class="bi bi-person"></i> Wykonawca:</b> @Model.Author</p>
                        <p class="mb-1 text-lg"><b><i class="bi bi-pen"></i> Nazwa:</b> @Model.Name</p>
                        <p class="mb-1 text-lg"><b><i class="bi bi-star"></i> Rok wydania:</b> @Model.Year</p>
                        <p class="mb-1 text-lg"><b><i class="bi bi-book"></i> Gatunek:</b> @Model.Genre</p>
                        <p class="text-lg"><i class="bi bi-hand-thumbs-up"></i> <b>Ocena użytkowników </b>(@Model.Ratings.Count):</p>

                        @if (Model.Ratings == null || Model.Ratings.Count == 0)
                        {
                            <div class="mt-2 flex justify-center space-x-1">
                                @for (int i = 0; i < 10; i++)
                                {
                                    <i class="bi bi-star text-2xl text-yellow-500"></i>
                                }
                            </div>
                        }
                        else
                        {
                            double avg = Model.Ratings.Average(a => a.Value);
                            double roundedAvg = Math.Round(avg * 2, MidpointRounding.AwayFromZero) / 2;
                            int fullStars = (int)roundedAvg;
                            bool hasHalfStar = roundedAvg - fullStars >= 0.5;

                            <div class="mt-2 flex justify-center space-x-1">
                                @for (int j = 0; j < fullStars; j++)
                                {
                                    <i class="bi bi-star-fill text-2xl text-yellow-500"></i>
                                }
                                @if (hasHalfStar)
                                {
                                    <i class="bi bi-star-half text-2xl text-yellow-500"></i>
                                    for (int i = fullStars + 1; i < 10; i++)
                                    {
                                        <i class="bi bi-star text-2xl text-yellow-500"></i>
                                    }
                                }
                                else
                                {
                                    for (int i = fullStars; i < 10; i++)
                                    {
                                        <i class="bi bi-star text-2xl text-yellow-500"></i>
                                    }
                                }
                            </div>
                        }

                        <hr class="my-4" />
                        @if (Model.UserRating == null)
                        {
                            <p class="text-lg font-semibold">Wystaw ocenę albumu:</p>
                            <div class="flex justify-center">
                                @for (int i = 0; i < 10; i++)
                                {
                                    <a asp-area="" asp-controller="Rating" asp-action="Create" asp-route-albumId="@Model.Id" asp-route-value="@(i+1)" class="bi bi-star m-0.5 text-2xl text-yellow-500 hover:scale-110 hover:text-yellow-600"></a>
                                }
                            </div>
                        }
                        else
                        {
                            <p class="text-lg font-semibold">Zmień ocenę albumu:</p>
                            <div class="flex justify-center text-blue-500">
                                @for (int i = 0; i < Model.UserRating.Value; i++)
                                {
                                    <a asp-area="" asp-controller="Rating" asp-action="Update" asp-route-albumId="@Model.Id" asp-route-ratingId="@Model.UserRating.Id" asp-route-value="@(i+1)" class="bi bi-star-fill m-0.5 text-2xl text-yellow-500 hover:scale-110 hover:text-yellow-600"></a>
                                }
                                @for (int i = Model.UserRating.Value; i < 10; i++)
                                {
                                    <a asp-area="" asp-controller="Rating" asp-action="Update" asp-route-albumId="@Model.Id" asp-route-ratingId="@Model.UserRating.Id" asp-route-value="@(i+1)" class="bi bi-star m-0.5 text-2xl text-yellow-500 hover:scale-110 hover:text-yellow-600"></a>
                                }
                            </div>
                        }
                    </div>
                </div>

                <!-- Right Column -->
                <div class="lg:col-span-2">
                    @if (ViewData["Error"] != null)
                    {
                        <div class="mb-4 rounded bg-red-500 p-3 text-white">
                            <p>@ViewData["Error"]</p>
                        </div>
                    }

                    <h2 class="mb-4 font-sans text-2xl">Wybrane recenzje albumu</h2>

                    @foreach (Review review in Model.Reviews)
                    {
                        <div class="mb-4 rounded bg-white p-4 shadow">
                            <div class="mb-2 flex items-center justify-between">
                                <p class="text-sm text-gray-600">Autor: @review.AppUser.UserName <span class="text-gray-400">(@review.CreatedAt.ToShortDateString())</span></p>
                                <div class="flex space-x-1">
                                    @for (int i = 0; i < review.Value; i++)
                                    {
                                        <i class="bi bi-star-fill text-xl text-yellow-500"></i>
                                    }
                                    @for (int i = review.Value; i < 10; i++)
                                    {
                                        <i class="bi bi-star text-xl text-yellow-500"></i>
                                    }
                                </div>
                            </div>
                            <h3 class="text-xl font-semibold">@review.Title</h3>
                            @if (review.Content.Length > 500)
                            {
                                <p>@review.Content.Substring(0, 500) ...</p>
                            }
                            else
                            {
                                <p>@review.Content</p>
                            }
                            <div class="mt-2 text-right">
                                <a asp-area="" asp-controller="Review" asp-action="Details" asp-route-id="@review.Id" class="font-semibold hover:text-blue-700">Czytaj całość <i class="bi bi-chevron-right"></i></a>
                            </div>
                        </div>
                    }
                    @if (!Model.IsReviewed)
                    {
                        <div class="mt-4 text-center">
                            <a class="rounded bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700" asp-area="" asp-controller="Review" asp-action="Create" asp-route-albumId="@Model.Id"><i class="bi bi-plus-lg"></i> Dodaj recenzję</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    <section class="py-4">
        <hr />
    </section>
</div>

music4you/Views/Album/Index.cshtml
@using music4you.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Album>
<section class="container py-5 text-center">

        <div class="mx-auto">
            <h1 class="text-4xl font-light">Przeglądaj z gamy naszych albumów</h1>

            @if (User.Identity.IsAuthenticated)
            {
                <p class="p-4 text-xl">

                    Jeśli nie ma albumu który cię interesuje, <a class="text-blue-400" asp-controller="Album" asp-action="Create" >
                        dodaj nowy album
                    </a>
                </p>
            }

        </div>
  
</section>
<form method="get" asp-action="Index">
    <div class="relative mx-auto max-w-80">
        <input type="text" name="search" id="search" class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-3 ps-10 text-lg text-gray-900 focus:ring-blue-500 focus:border-blue-500" placeholder="Szukaj..." value="@Context.Request.Query["search"]" />
        <button type="submit" class="absolute bottom-1 end-1 rounded-lg bg-blue-700 px-3 py-3 text-sm text-white hover:bg-blue-800 focus:ring-4 focus:ring-blue-300"><i class="bi bi-search"></i></button>
    </div>
</form>
<div class="album bg-body-tertiary mt-1 py-5">
    <div class="container">
        @if (!string.IsNullOrEmpty(Context.Request.Query["search"]))
        {
            <div class="mb-8 p-6">
                <h1 class="text-2xl text-gray-500">Wyniki dla frazy: '@Context.Request.Query["search"]'</h1>
            </div>
        }
        
        @if(Model.Count == 0)
        {
            <h3 class="text-secondary lead text-center"><i class="bi bi-info-circle p-2"></i> Nie znaleziono takiego albumu...</h3>
        }
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-3">
            
            @foreach (Album album in Model)
            {
                string url;
                try
                {
                    url = album.ImageUrl;
                }
                catch (Exception ex)
                {
                    url = "https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png";
                }
                <div class="col">
                    <div class="card album-card position-relative shadow-sm">
                        <div class="aspect-square w-full overflow-hidden bg-gray-200">
                            <a asp-controller="Album" asp-action="Details" asp-route-id="@album.Id">
                                <img src="@url"
                                     alt="Obraz przedstawiający @album.Name"
                                     class="rounded-md object-cover card-img-top aspect-square" style="height: 340px;" />
                            </a>
                        </div>
                        <div class="card-body">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                            {
                                <a type="button" asp-controller="Album" asp-action="Edit" asp-route-id="@album.Id"
                                   class="btn btn-sm btn-outline-secondary position-absolute end-0 top-0 m-2">
                                    <i class="bi bi-pencil-fill"></i>
                                </a>
                            }
                            <div class="text-center">
                                <a class="text-secondary fst-italic" style="text-decoration: none;" asp-controller="Album" asp-action="Details" asp-route-id="@album.Id">@album.Author</a>
                                <p><a class="line-clamp-1 gray decoration-0 w-full text-xl font-semibold text-gray-600" asp-controller="Album" asp-action="Details" asp-route-id="@album.Id">@album.Name</a></p>
                            </div>
                            <div class="my-2 text-center">
                                @if (album.Ratings == null || album.Ratings.Count() == 0)
                                {
                                    @for (int i = 0; i < 10; i++)
                                    {
                                        <i class="bi bi-star text-xl text-yellow-500"></i>
                                    }
                                }
                                else
                                {
                                    double avg = album.Ratings.Average(a => a.Value);
                                    double roundedAvg = Math.Round(avg * 2, MidpointRounding.AwayFromZero) / 2;
                                    int fullStars = (int)roundedAvg;
                                    bool hasHalfStar = roundedAvg - fullStars >= 0.5;

                                    @for (int j = 0; j < fullStars; j++)
                                    {
                                        <i class="bi bi-star-fill text-xl text-yellow-500"></i>
                                    }
                                    @if (hasHalfStar)
                                    {
                                        <i class="bi bi-star-half text-xl text-yellow-500"></i>
                                    }
                                    for (int i = fullStars + (hasHalfStar ? 1 : 0); i < 10; i++)
                                    {
                                        <i class="bi bi-star text-xl text-yellow-500"></i>
                                    }
                                }
                            </div>
                            <p class="text-muted text-center" style="font-size: 18px;">@album.Year</p>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>